// Auto-generated by nkunziyenugu_systems/scripts/build-permissions-registry.js
// Do NOT edit by hand — regenerate with: npm run build:perms
//
// Typed name maps so callers get compile-time-checked permission names.
// Use:  canRoute(P.ShopDashboard)  /  canAction(A.view)

export const P = {
  MainDashboard: 'MainDashboard',
  UserList: 'UserList',
  AddUser: 'AddUser',
  EditUser: 'EditUser',
  EditPermissions: 'EditPermissions',
  Accounts: 'Accounts',
  AddAccount: 'AddAccount',
  EditAccount: 'EditAccount',
  AuditLogs: 'AuditLogs',
  DevicesList: 'DevicesList',
  AddDevice: 'AddDevice',
  DeviceLogs: 'DeviceLogs',
  ShopDashboard: 'ShopDashboard',
  ShopProducts: 'ShopProducts',
  ShopCart: 'ShopCart',
  ShopMyOrders: 'ShopMyOrders',
  AdminOrders: 'AdminOrders',
  ShopPOS: 'ShopPOS',
  ShopSalesSummary: 'ShopSalesSummary',
  ShopCashFlow: 'ShopCashFlow',
  AddProduct: 'AddProduct',
  CustomerCredit: 'CustomerCredit',
  CustomerCreditRequests: 'CustomerCreditRequests',
  FarmDashboard: 'FarmDashboard',
  FarmList: 'FarmList',
  AddFarm: 'AddFarm',
  EditFarm: 'EditFarm',
  AnimalList: 'AnimalList',
  InventoryView: 'InventoryView',
  PnlReport: 'PnlReport',
  AddAnimal: 'AddAnimal',
  EditAnimal: 'EditAnimal',
  AddAnimalEvent: 'AddAnimalEvent',
  AnimalEventList: 'AnimalEventList',
  AnimalDeviceLink: 'AnimalDeviceLink',
  AnimalTypeList: 'AnimalTypeList',
  AddAnimalType: 'AddAnimalType',
  EditAnimalType: 'EditAnimalType',
  AnimalBreedList: 'AnimalBreedList',
  AddAnimalBreed: 'AddAnimalBreed',
  EditAnimalBreed: 'EditAnimalBreed'
} as const;

export const A = {
  view: 'view',
  add: 'add',
  edit: 'edit',
  delete: 'delete',
  approve: 'approve',
  complete: 'complete',
  assign: 'assign',
  configure: 'configure'
} as const;

export type RouteName = typeof P[keyof typeof P];
export type ActionName = typeof A[keyof typeof A];
