<?php

namespace App\Http\Controllers\Api;

use App\Models\ShopPosCart;
use App\Models\ShopPosCartItem;
use App\Models\ShopPosSale;
use App\Models\ShopPosSaleItem;
use App\Models\ShopProduct;
use App\Models\ShopCustomer;
use App\Models\ShopCashflow;
use App\Services\AuditLogService;
use App\Support\Money;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\ValidationException;

class ShopPosController extends ShopBaseController
{
    public function getOpenCart(Request $request)
    {
        $accountId = $this->requireActiveAccountId($request);

        $this->requireAccountAccess($request, $accountId);

        $userId = $request->user()->id;

        $cart = ShopPosCart::with('items.product')
            ->where('account_id', $accountId)
            ->where('cashier_user_id', $userId)
            ->where('status', 'open')
            ->first();

        if (!$cart) {
            $cart = ShopPosCart::create([
                'account_id' => $accountId,
                'cashier_user_id' => $userId,
                'status' => 'open',
            ]);
            $cart->load('items.product');
        }

        return response()->json(['status' => 'success', 'data' => $cart]);
    }

    public function addItem(Request $request)
    {
        $accountId = $this->requireActiveAccountId($request);

        $this->requireAccountAccess($request, $accountId);

        $request->validate([
            'product_id' => 'required|exists:shop_products,id',
            'qty' => 'required|integer|min:1',
        ]);

        $userId = $request->user()->id;

        $cart = ShopPosCart::firstOrCreate([
            'account_id' => $accountId,
            'cashier_user_id' => $userId,
            'status' => 'open',
        ]);

        $product = ShopProduct::where('id', $request->product_id)
            ->where('account_id', $accountId)
            ->where('deleted', false)
            ->first();

        if (!$product) {
            return response()->json(['status' => 'error', 'message' => 'Product not found'], 404);
        }

        $qty = (int) $request->qty;

        $item = ShopPosCartItem::where('pos_cart_id', $cart->id)
            ->where('product_id', $product->id)
            ->first();

        if ($item) {
            $item->qty += $qty;
        } else {
            $item = new ShopPosCartItem([
                'pos_cart_id' => $cart->id,
                'product_id' => $product->id,
                'qty' => $qty,
                'pre_stock_level' => (int) $product->stock_level,
                'prof_per_product' => (float) $product->prof_per_product,
            ]);
        }

        $item->unit_price = $product->actual_price;
        $item->total_price = $item->qty * $item->unit_price;
        $item->save();

        $cart->load('items.product');
        return response()->json(['status' => 'success', 'data' => $cart]);
    }

    public function updateItem(Request $request, ShopPosCartItem $item)
    {
        $accountId = $this->requireActiveAccountId($request);

        $this->requireAccountAccess($request, $accountId);

        $request->validate([
            'qty' => 'required|integer|min:1',
        ]);

        $item->load('cart');
        if ((int) $item->cart->account_id !== $accountId) {
            return response()->json(['status' => 'error', 'message' => 'Item not found'], 404);
        }

        $item->qty = (int) $request->qty;
        $item->total_price = $item->qty * $item->unit_price;
        $item->save();

        $item->cart->load('items.product');
        return response()->json(['status' => 'success', 'data' => $item->cart]);
    }

    public function removeItem(Request $request, ShopPosCartItem $item)
    {
        $accountId = $this->requireActiveAccountId($request);

        $this->requireAccountAccess($request, $accountId);

        $item->load('cart');
        if ((int) $item->cart->account_id !== $accountId) {
            return response()->json(['status' => 'error', 'message' => 'Item not found'], 404);
        }

        $cart = $item->cart;
        $item->delete();

        $cart->load('items.product');
        return response()->json(['status' => 'success', 'data' => $cart]);
    }

    public function checkout(Request $request)
    {
        $accountId = $this->requireActiveAccountId($request);

        $this->requireAccountAccess($request, $accountId);

        $request->validate([
            'payment_method'   => 'required|string|in:Cash,Cash Deposit,Credit',
            'customer_id'      => 'nullable|integer',
            'customer_name'    => 'nullable|string|max:255',
            'customer_phone'   => 'nullable|string|max:50',
            'amount_received'  => 'nullable|numeric|min:0',
            'payment_proof'    => 'nullable|file|mimes:jpg,jpeg,png,pdf|max:5120',
            // UUID generated by the POS frontend per cart. Same value on a
            // retry → backend returns the existing sale instead of creating
            // a duplicate.
            'idempotency_key'  => 'nullable|uuid',
        ]);

        // ── Idempotency short-circuit ────────────────────────────────────
        // If the client sends the same key twice (double-click, network
        // retry, browser back/forward) return the original sale with 200.
        $idemKey = $request->input('idempotency_key');
        if ($idemKey) {
            $existing = ShopPosSale::where('account_id', $accountId)
                ->where('idempotency_key', $idemKey)
                ->first();
            if ($existing) {
                return response()->json([
                    'status'    => 'success',
                    'data'      => $existing->load(['items', 'cashier', 'customer']),
                    'duplicate' => true,
                ]);
            }
        }

        $proofPath = null;
        if ($request->hasFile('payment_proof')) {
            $proofPath = $request->file('payment_proof')->store(
                "shop/pos/proof/{$request->header('X-Account-ID')}",
                'public'
            );
        }

        $userId = $request->user()->id;

        $cart = ShopPosCart::with('items.product')
            ->where('account_id', $accountId)
            ->where('cashier_user_id', $userId)
            ->where('status', 'open')
            ->first();

        if (!$cart || $cart->items->isEmpty()) {
            return response()->json(['status' => 'error', 'message' => 'Cart is empty'], 400);
        }

        // ── Pre-flight validation that doesn't need DB writes ────────────
        // Done OUTSIDE the transaction so failure paths don't have to worry
        // about rollback / mid-transaction response leaks.
        $paymentMethod  = (string) $request->payment_method;
        $isPaid         = $paymentMethod !== 'Credit';
        $customerId     = $request->customer_id !== null ? (int) $request->customer_id : null;
        $customerName   = $request->customer_name;
        $customerPhone  = $request->customer_phone;
        $amountReceived = $request->amount_received;

        if ($paymentMethod === 'Credit') {
            if (!$customerId) {
                return response()->json(['status' => 'error', 'message' => 'customer_id is required for Credit sales'], 422);
            }
            $customer = ShopCustomer::where('id', $customerId)
                ->where('account_id', $accountId)
                ->where('deleted', false)
                ->first();
            if (!$customer) {
                return response()->json(['status' => 'error', 'message' => 'Customer not found'], 422);
            }
            $customerName  = $customer->name;
            $customerPhone = $customer->phone;
            // Credit limit pre-flight check (the locked-balance enforcement
            // also runs inside the transaction below — this just gives the
            // user a fast 422 before we try to lock products).
            if ((float) $customer->credit_limit <= 0) {
                return response()->json([
                    'status'  => 'error',
                    'message' => 'Customer is not approved for credit (credit_limit is 0).',
                ], 422);
            }
        } elseif ($customerId) {
            $customer = ShopCustomer::where('id', $customerId)
                ->where('account_id', $accountId)
                ->where('deleted', false)
                ->first();
            if ($customer) {
                $customerName  = $customerName  ?: $customer->name;
                $customerPhone = $customerPhone ?: $customer->phone;
            }
        }

        if ($paymentMethod !== 'Credit' && $amountReceived === null) {
            return response()->json(['status' => 'error', 'message' => 'amount_received is required for this payment method'], 422);
        }

        // ── Transactional write path ─────────────────────────────────────
        // Throws on validation failure → triggers rollback. Returns the
        // built sale on success. The HTTP response is built OUTSIDE so
        // we never `return response()->json()` from inside the closure.
        try {
            $sale = DB::transaction(function () use (
                $request, $accountId, $userId, $cart, $paymentMethod, $isPaid,
                $customerId, $customerName, $customerPhone, $amountReceived,
                $proofPath, $idemKey
            ) {
                // Lock ALL products in the cart in one query — closes the
                // TOCTOU window where two concurrent checkouts both pass
                // an unlocked stock check then race on decrement.
                $productIds = $cart->items->pluck('product_id')->all();
                $products = ShopProduct::whereIn('id', $productIds)
                    ->where('account_id', $accountId)
                    ->lockForUpdate()
                    ->get()
                    ->keyBy('id');

                // Compute totals with locked stock in integer cents.
                $totalCents  = 0;
                $profitCents = 0;
                foreach ($cart->items as $item) {
                    $product = $products->get($item->product_id);
                    if (!$product || $product->deleted) {
                        throw new \RuntimeException('Product missing');
                    }
                    if ((int) $product->stock_level < (int) $item->qty) {
                        throw new \RuntimeException("Insufficient stock for {$product->product_name}");
                    }
                    $totalCents  += Money::toCents($item->total_price);
                    $profitCents += Money::toCents($item->prof_per_product) * (int) $item->qty;
                }

                // Validate amount_received against the LOCKED total in cents.
                $changeCents = null;
                $receivedCents = null;
                if ($paymentMethod !== 'Credit') {
                    $receivedCents = Money::toCents($amountReceived);
                    if ($receivedCents < $totalCents) {
                        throw new \RuntimeException('Amount received is less than total');
                    }
                    $changeCents = $receivedCents - $totalCents;
                }

                // Credit-limit enforcement on the LOCKED customer row, so two
                // concurrent credit sales can't both squeak under the limit.
                if ($paymentMethod === 'Credit') {
                    $lockedCustomer = ShopCustomer::where('id', $customerId)
                        ->where('account_id', $accountId)
                        ->lockForUpdate()
                        ->first();
                    if (!$lockedCustomer) {
                        throw new \RuntimeException('Customer not found');
                    }
                    $limitCents = Money::toCents($lockedCustomer->credit_limit);
                    $usedCents  = Money::toCents($lockedCustomer->credit_used);
                    if ($limitCents <= 0) {
                        throw new \RuntimeException('Customer is not approved for credit.');
                    }
                    if ($usedCents + $totalCents > $limitCents) {
                        $remaining = Money::fromCents(max(0, $limitCents - $usedCents));
                        throw new \RuntimeException(
                            "Credit limit exceeded. Remaining credit: R{$remaining}"
                        );
                    }
                    // Bump credit_used; will be decremented again in markSalePaid.
                    $lockedCustomer->credit_used = Money::fromCents($usedCents + $totalCents);
                    $lockedCustomer->save();
                }

                $sale = ShopPosSale::create([
                    'account_id'         => $accountId,
                    'idempotency_key'    => $idemKey,
                    'cashier_user_id'    => $userId,
                    'customer_id'        => $customerId,
                    'customer_name'      => $customerName,
                    'customer_phone'     => $customerPhone,
                    'payment_method'     => $paymentMethod,
                    'amount_received'    => $receivedCents !== null ? Money::fromCents($receivedCents) : null,
                    'change_amount'      => $changeCents   !== null ? Money::fromCents($changeCents)   : null,
                    'total_amount'       => Money::fromCents($totalCents),
                    'total_profit'       => Money::fromCents($profitCents),
                    'sale_datetime'      => now(),
                    'is_paid'            => $isPaid,
                    'paid_at'            => $isPaid ? now() : null,
                    'paid_method'        => $isPaid ? $paymentMethod : null,
                    'paid_amount'        => $isPaid ? Money::fromCents($totalCents) : null,
                    'payment_proof_path' => $proofPath,
                ]);

                AuditLogService::logCreate($sale, $request, 'Created POS sale');

                // Decrement stock + create sale items on the already-locked
                // product rows. No second stock check needed — already
                // validated above under the same lock.
                foreach ($cart->items as $item) {
                    $product = $products->get($item->product_id);

                    ShopPosSaleItem::create([
                        'pos_sale_id'      => $sale->id,
                        'product_id'       => $product->id,
                        'product_name'     => $product->product_name,
                        'product_type'     => $product->product_type,
                        'qty_sold'         => $item->qty,
                        'actual_price'     => $item->unit_price,
                        'total_price'      => $item->total_price,
                        'prof_per_product' => $item->prof_per_product,
                    ]);

                    $product->stock_level = (int) $product->stock_level - (int) $item->qty;
                    $product->save();
                }

                $cart->status = 'checked_out';
                $cart->customer_name = $customerName;
                $cart->save();
                $cart->items()->delete();

                return $sale;
            });
        } catch (\RuntimeException $e) {
            return response()->json(['status' => 'error', 'message' => $e->getMessage()], 422);
        } catch (\Illuminate\Database\QueryException $e) {
            // Catches a race on the unique (account_id, idempotency_key)
            // index — two concurrent retries with the same key. Re-fetch
            // the row that was written first and return it as the
            // canonical response.
            if ($idemKey && str_contains($e->getMessage(), 'shop_pos_sales_idem_unique')) {
                $existing = ShopPosSale::where('account_id', $accountId)
                    ->where('idempotency_key', $idemKey)
                    ->first();
                if ($existing) {
                    return response()->json([
                        'status'    => 'success',
                        'data'      => $existing->load(['items', 'cashier', 'customer']),
                        'duplicate' => true,
                    ]);
                }
            }
            throw $e;
        }

        return response()->json([
            'status' => 'success',
            'data'   => $sale->load(['items', 'cashier', 'customer']),
        ]);
    }

    public function markSalePaid(Request $request, ShopPosSale $sale)
    {
        $accountId = $this->requireActiveAccountId($request);

        $this->requireAccountAccess($request, $accountId);

        if ((int) $sale->account_id !== $accountId) {
            return response()->json(['status' => 'error', 'message' => 'Not found'], 404);
        }

        $request->validate([
            'paid_method' => 'required|string|in:Cash,Cash Deposit',
        ]);

        if ((string) $sale->payment_method !== 'Credit') {
            return response()->json(['status' => 'error', 'message' => 'Only Credit sales can be marked as paid'], 400);
        }

        if ((bool) $sale->is_paid) {
            return response()->json(['status' => 'error', 'message' => 'Sale is already marked as paid'], 400);
        }

        $userId = $request->user()->id;
        $paidMethod = (string) $request->paid_method;

        try {
            $sale = DB::transaction(function () use ($request, $sale, $accountId, $userId, $paidMethod) {
                $oldValues = $sale->getAttributes();
                $sale->is_paid = true;
                $sale->paid_at = now();
                $sale->paid_method = $paidMethod;
                $sale->paid_amount = $sale->total_amount;
                $sale->save();

                // Decrement credit_used on the linked customer (locked) so
                // the available balance reflects the payoff. Clamps at 0.
                if ($sale->customer_id) {
                    $customer = ShopCustomer::where('id', $sale->customer_id)
                        ->where('account_id', $sale->account_id)
                        ->lockForUpdate()
                        ->first();
                    if ($customer) {
                        $usedCents = Money::toCents($customer->credit_used);
                        $payCents  = Money::toCents($sale->total_amount);
                        $newUsed   = max(0, $usedCents - $payCents);
                        $customer->credit_used = Money::fromCents($newUsed);
                        $customer->save();
                    }
                }

                AuditLogService::logUpdate($sale, $oldValues, $request, 'Marked Credit sale as paid');

                return $sale;
            });
        } catch (\RuntimeException $e) {
            return response()->json(['status' => 'error', 'message' => $e->getMessage()], 422);
        }

        return response()->json([
            'status' => 'success',
            'data'   => $sale->fresh()->load(['items', 'cashier', 'customer']),
        ]);
    }

    public function updateSale(Request $request, ShopPosSale $sale)
    {
        $accountId = $this->requireActiveAccountId($request);

        $this->requireAccountAccess($request, $accountId);

        if ((int) $sale->account_id !== $accountId) {
            return response()->json(['status' => 'error', 'message' => 'Not found'], 404);
        }

        $request->validate([
            'customer_name' => 'required|string|max:255',
            'customer_phone' => 'nullable|string|max:50',
        ]);

        $oldValues = $sale->getAttributes();

        $sale->customer_name = $request->customer_name;
        if ($request->has('customer_phone')) {
            $sale->customer_phone = $request->customer_phone;
        }
        $sale->save();

        AuditLogService::logUpdate($sale, $oldValues, $request, 'Updated POS sale customer name');

        return response()->json(['status' => 'success', 'data' => $sale->fresh()->load(['items', 'cashier', 'customer'])]);
    }

    public function salesReport(Request $request)
    {
        $accountId = $this->requireActiveAccountId($request);

        $this->requireAccountAccess($request, $accountId);

        $request->validate([
            'from' => 'required|date',
            'to' => 'required|date',
        ]);

        $from = Carbon::parse($request->from)->startOfDay();
        $to = Carbon::parse($request->to)->endOfDay();

        $sales = ShopPosSale::with(['items', 'cashier', 'customer'])
            ->where('account_id', $accountId)
            ->whereBetween('sale_datetime', [$from, $to])
            ->orderByDesc('sale_datetime')
            ->get();

        return response()->json(['status' => 'success', 'data' => $sales]);
    }

    public function updateSaleItem(Request $request, ShopPosSaleItem $item)
    {
        $accountId = $this->requireActiveAccountId($request);

        $this->requireAccountAccess($request, $accountId);

        $request->validate([
            'prof_per_product' => 'required|numeric',
        ]);

        $item->load('sale.items');

        if (!$item->sale || (int) $item->sale->account_id !== $accountId) {
            return response()->json(['status' => 'error', 'message' => 'Not found'], 404);
        }

        return DB::transaction(function () use ($request, $item) {
            $oldItemValues = $item->getAttributes();
            $item->prof_per_product = (float) $request->prof_per_product;
            $item->save();

            AuditLogService::logUpdate($item, $oldItemValues, $request, 'Updated POS sale item profit');

            $sale = $item->sale;
            $sale->load('items');

            $totalProfit = 0;
            foreach ($sale->items as $saleItem) {
                $totalProfit += ((float) $saleItem->prof_per_product * (int) $saleItem->qty_sold);
            }

            $oldSaleValues = $sale->getAttributes();
            $sale->total_profit = $totalProfit;
            $sale->save();

            AuditLogService::logUpdate($sale, $oldSaleValues, $request, 'Updated POS sale total profit');

            return response()->json([
                'status' => 'success',
                'data' => $sale->load(['items', 'cashier', 'customer']),
            ]);
        });
    }
}
